### ISSUE TITLE
博客的gitment评论开启一直失败

### ISSUE THREAD

**Issue by JJXiangJiaoJun** [ZEROKISEKI/hexo-theme-gal#47]
按照教程上配的，我的github pages绑定了个人域名
`https//:hongbb.top`
OAuth配置如下，应该是没有错误的
![image](https://user-images.githubusercontent.com/37390337/51407028-c58dea80-1b95-11e9-98d3-622b327f157e.png)
_config.yml的配置如下，保证client_id 和 client_secret没有填错
```
comment:
  gitment:
    enable: true
    owner: 'JJXiangJiaoJun' # 必填项, 你的GitHub ID
    repo: 'JJXiangJiaoJun.github.io' # 必填项  你的存储评论的repo
    oauth:
      client_id: 'd7df3d5d159f81371d76' # 必填项
      client_secret: '3794527fca067871d3795782ae7fd14f94ce3a74' # 必填项
      redirect_uri: # 可以填也可以不填

```
设置后博客上显示　`Error: Comments Not Initialized`

点击　登录　按钮后，无法跳转到github授权界面
浏览器上信息为 `https://hongbb.top/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch`

看起来好像是call-back url填错了,不过我试了 原来的ＵＲＬ也没用
