### ISSUE TITLE
hexo favicon怎么修改，本人新手，在谷歌搜索一大圈，无果，所以才来问一下

### ISSUE THREAD

**Issue by Xkwfsxfwa** [ZEROKISEKI/hexo-theme-gal#72]

**Comment by Xkwfsxfwa** [comment]
> _没有提供描述。_

问题已经解决，打扰了

**Comment by Xkwfsxfwa** [comment]
对了还有一个问题
![TIM截图20200131131321](https://user-images.githubusercontent.com/54878757/73514184-aa51ee00-442b-11ea-9a9a-b68551b4284a.png)
头像下面该怎么显示字？

**Comment by hkjjsgdd** [comment]
favicon是怎么解决的 我想知道 ？

**Comment by Xkwfsxfwa** [comment]
> favicon是怎么解决的 我想知道 ？

现在我不玩hexo了，忘了怎么弄的了

**Comment by fnsflm** [comment]
> 对了还有一个问题
> ![TIM截图20200131131321](https://user-images.githubusercontent.com/54878757/73514184-aa51ee00-442b-11ea-9a9a-b68551b4284a.png)
> 头像下面该怎么显示字？

在站点的`_config.yml`下修改description, 不是主题的config
```yml
# Site
title: Hello World
subtitle: ''
description: ''
keywords:
author: FNSFLM
language: en
timezone: ''
```
