### ISSUE TITLE
那个评论点击登录后跳转到github是怎么评论？

### ISSUE THREAD

**Issue by shawsw** [ZEROKISEKI/hexo-theme-gal#76]

**Comment by fnsflm** [comment]
点击登录会跳转一个链接, 比如:
`https://github.com/login/oauth/authorize?scope=public_repo&redirect_uri=https://myau.moe/2018/04/23/StarsManager/&client_id=27d3fea0ef621e9ff1e6&client_secret=1c953686c8acde73f925162eb81c229ab4b7ec58`
其中有个`redirect_uri`参数, 在登录完成后会跳转到这个链接上.
而在主题的配置文件`_config.yml`有redirect_uri这一下, 检查是否填错
```
comment:
  gitment:
      owner: # 必填项, 你的GitHub ID
      repo:  # 必填项  你的存储评论的repo名称(不是整个的地址)
      oauth:
        client_id:  # 必填项
        client_secret: # 必填项
        redirect_uri: # 可以填也可以不填
```
如果还有问题, 请至少提供站点地址
(还是放弃gitment吧)
